#!/usr/bin/env bash
# SuperCarl — post-deploy setup: API key, delivery targets, observability.
set -euo pipefail

REGION="${AWS_DEFAULT_REGION:-us-east-1}"
PROFILE="${AWS_PROFILE:-}"
AWS_OPTS="--region $REGION"
[[ -n "$PROFILE" ]] && AWS_OPTS="$AWS_OPTS --profile $PROFILE"

echo "=========================================="
echo " SuperCarl — Post-Deploy Setup"
echo "=========================================="
echo ""
echo "[1/4] Set your SuperCarl API key"
echo "  aws secretsmanager put-secret-value --secret-id supercarl/api-key \\"
echo "    --secret-string '{\"api_key\":\"YOUR_KEY\"}' $AWS_OPTS"
echo ""
echo "[2/4] (Optional) Set Slack/Teams webhook for delivery"
echo "  aws secretsmanager put-secret-value --secret-id supercarl/slack-webhook \\"
echo "    --secret-string '{\"webhook_url\":\"https://hooks.slack.com/...\"}' $AWS_OPTS"
echo ""
echo "[3/4] (Optional) Configure SES delivery"
echo "  - Verify a sender identity in SES (sandbox: verify recipient too)."
echo "  - Set env on the deliver_results Lambda:"
echo "      aws lambda update-function-configuration --function-name supercarl_deliver_results \\"
echo "        --environment 'Variables={SES_SENDER=you@verified.com,SES_RECIPIENT=team@you.com}' $AWS_OPTS"
echo ""
echo "[4/4] Enable CloudWatch Transaction Search (for OTEL traces)"
echo "  CloudWatch Console > Settings > Transaction Search > Enable"
echo ""
echo "Point executors at the real SuperCarl API once it's live (end of Week 1):"
echo "  Set SUPERCARL_API_BASE_URL on each supercarl_* executor Lambda, or"
echo "  redeploy with SUPERCARL_API_BASE_URL exported."
echo ""
echo "Done."
